FROM quay.io/centos/centos:stream10-minimal

RUN sed -i 's|\,http||g' /etc/yum.repos.d/* && \
    microdnf install -y haproxy && \
    microdnf clean all

# Create a non-root user for haproxy
RUN useradd -r -s /sbin/nologin haproxy

# Allow binding to privileged ports as non-root
RUN setcap 'cap_net_bind_service=+ep' /usr/sbin/haproxy

COPY haproxy.cfg /etc/haproxy/haproxy.cfg

EXPOSE 80/tcp
EXPOSE 443/tcp
EXPOSE 80/udp
EXPOSE 443/udp

USER haproxy

CMD ["/usr/sbin/haproxy", "-f", "/etc/haproxy/haproxy.cfg", "-db"]
